# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  
  - openjdk11
services:
  - postgresql
  before_install:
    - psql -c 'create database tracker;' -U postgres

# используем режим обычного пользователя для сборки проекта.
sudo: false
after_success:
  - bash <(curl -s https://codecov.io/bash)
# Отправлять уведомление на почту vovk.ag747@gmail.com если сборка упала
notifications:
  email:
    recipients:
      -vovk.ag747@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
  env:
    global:
      - CODECOV_TOKEN="e94dbf91-6934-4c5c-b225-324b30ab4b77"